-- PREDICADOS IN Y NOT IN

SELECT NOMBREARTÍCULO, PRECIO
FROM PRODUCTOS
WHERE CÓDIGOARTÍCULO
IN (SELECT CÓDIGOARTÍCULO FROM PRODUCTOSPEDIDOS WHERE UNIDADES > 20);

SELECT NOMBREARTÍCULO, PRECIO
FROM PRODUCTOS
INNER JOIN PRODUCTOSPEDIDOS
ON PRODUCTOS.CÓDIGOARTÍCULO = PRODUCTOSPEDIDOS.CÓDIGOARTÍCULO
WHERE UNIDADES > 20;

SELECT EMPRESA, POBLACIÓN
FROM CLIENTES
WHERE CÓDIGOCLIENTE 
NOT IN (SELECT CÓDIGOCLIENTE FROM PEDIDOS WHERE FORMADEPAGO = 'TARJETA');

