-- AGREGAR, ELIMINAR, MODIFICAR CAMPOS

ALTER TABLE CLIENTES_MADRID
ADD COLUMN FECHA_BAJA VARCHAR;

ALTER TABLE CLIENTES_MADRID
ALTER COLUMN FECHA DATE;


---------------------------------------

ALTER TABLE PRUEBA
ADD COLUMN POBLACIÓN VARCHAR(20);

ALTER TABLE PRUEBA 
ADD COLUMN LUGAR_NACIMIENTO VARCHAR(20);

ALTER TABLE PRUEBA
ALTER COLUMN LUGAR_NACIMIENTO 
SET DEFAULT 'DESCONOCIDO';

ALTER TABLE PRUEBA
ALTER COLUMN LUGAR_NACIMIENTO
DROP DEFAULT;

ALTER TABLE PRUEBA
DROP COLUMN POBLACIÓN;

-- ACCESS NO SOPORTA DROP Y SET DEFAULT

