-- CONSULTAS MULTITABLA / CONSULTAS DE UNIÓN
  -- UNIÓN EXTERNA:
    -- UNION
    -- UNION ALL
    ------- NO SOPORTADO POR TODOS LOS GESTORES DB COMO (MYSQL Y ACCESS) -------
    -- EXCEPT
    -- INTERSECT
    -- MINUS

SELECT * FROM PRODUCTOS WHERE SECCIÓN ="DEPORTES" 
UNION SELECT * FROM PRODUCTOSNUEVOS WHERE SECCIÓN = "DEPORTES DE RIESGO";

SELECT * FROM PRODUCTOS WHERE SECCIÓN ="DEPORTES" 
UNION ALL SELECT * FROM PRODUCTOSNUEVOS WHERE SECCIÓN = "DEPORTES DE RIESGO";

-- UNION OMITE REPETIDOS, AL CONTRARIO DE UNION ALL QUE NO LOS OMITE
-- LAS TABLAS TIENEN QUE TENER EL MISMO NÚMERO DE CAMPOS Y EL LOS CAMPOS TIENEN QUE SER
-- DE TIPO DE DATOS COMPATIBLES PARA PODER REALIZAR CONSULTAS DE ESTE TIPO


