-- CONSULTAS DE ACCIÓN

-- DATOS ANEXADOS

-- ACCESS Y MYSQL
INSERT INTO CLIENTES 
SELECT * 
FROM CLIENTES_MADRID;

DELETE FROM CLIENTES
WHERE POBLACIÓN = 'MADRID';

INSERT INTO (CÓDIGOCLIENTE, EMPRESA, POBLACIÓN, TELÉFONO)
SELECT CÓDIGOCLIENTE, EMPRESA, POBLACIÓN, TELÉFONO
FROM CLIENTES_MADRID;