-- PROCEDIMIENTO Y TRIGGERS

-- declaración de variables en procedimientos
-- EJEMPLO

DELIMITER $$
CREATE PROCEDURE CALCULA_EDAD(AGNO_NACIMIENTO INT)
  BEGIN

    DECLARE AGNO_ACTUAL INT DEFAULT 2020;
    DECLARE EDAD INT;
    SET EDAD = AGNO_ACTUAL - AGNO_NACIMIENTO;
    SELECT EDAD;

  END;$$
  DELIMITER ;

  -- ; delimitador por defecto
  -- $$ ó // delimitador de bloque


  -- EJEMPLO
  DROP TRIGGER IF EXISTS REVISA_PRECIO_BU;
  DELIMITER $$
  CREATE TRIGGER REVISA_PRECIO_BU
  BEFORE UPDATE
  ON PRODUCTOS
  FOR EACH ROW
    BEGIN
      IF(NEW.PRECIO < 0) THEN
        SET NEW.PRECIO = OLD.PRECIO;
      ELSEIF(NEW.PRECIO >1000) THEN
        SET NEW.PRECIO = OLD.PRECIO;
      END IF;
    END;$$
  DELIMITER ;

  UPDATE PRODUCTOS
  SET PRECIO = 6.83
  WHERE CÓDIGOARTÍCULO = 'AR01';

  UPDATE PRODUCTOS
  SET PRECIO = -15
  WHERE CÓDIGOARTÍCULO = 'AR01';