-- CONSULTAS MULTITABLA / CONSULTAS DE UNIÓN 
  -- UNIÓN INTERNA
    -- INNER JOIN
    -- LEFT JOIN
    -- RIGHT JOIN

    -- LEFT JOIN Y RIGHT JOIN SE LES CONOCE TAMBIEN COMO OUTER JOIN


    -- EJEMPLO INNER JOIN
    SELECT * 
    FROM CLIENTES
    INNER JOIN PEDIDOS
    ON CLIENTES.CÓDIGOCLIENTE = PEDIDOS.[CÓDIGO CLIENTE]
    WHERE POBLACIÓN = "MADRID";

    SELECT CLIENTES.CÓDIGOCLIENTE, POBLACIÓN, DIRECCIÓN, NÚMERODEPEDIDO,
    PEDIDOS.CÓDIGOCLIENTE, FORMADEPAGO
    FROM CLIENTES
    INNER JOIN PEDIDOS
    ON CLIENTES.CÓDIGOCLIENTE = PEDIDOS.CÓDIGOCLIENTE
    WHERE POBLACIÓN="MADRID";

    -- EJEMPLO LEFT JOIN
    SELECT * 
    FROM CLIENTES
    LEFT JOIN PEDIDOS
    ON CLIENTES.CÓDIGOCLIENTE = PEDIDOS.[CÓDIGO CLIENTE]
    WHERE POBLACIÓN = "MADRID";


    SELECT CLIENTES.CÓDIGOCLIENTE, POBLACIÓN, DIRECCIÓN, NÚMERODEPEDIDO,
    PEDIDOS.CÓDIGOCLIENTE, FORMADEPAGO
    FROM CLIENTES
    LEFT JOIN PEDIDOS
    ON CLIENTES.CÓDIGOCLIENTE = PEDIDOS.CÓDIGOCLIENTE
    WHERE POBLACIÓN="MADRID" AND PEDIDOS.CÓDIGOCLIENTE IS NULL;
