-- TRIGGERS (DISPARADORES)
  -- es un objeto creado en la bd asociado a una
  -- tabla que desencadena una accion cuando  alguien
  -- haga insert, update, delete.
  -- se usan para tareas de mantenimiento y
  -- administración en bd.
  -- access no lo soporta pero tienen sus macros
  -- para simularlo.

  -- TIPOS
    -- AFTER, BEFORE: (INSERT, UPDATE, DELETE)


-- EJEMPLO:

-- TRIGGER DE INSERCCIÓN
   CREATE TABLE REG_PRODUCTOS(
     CÓDIGOARTÍCULO VARCHAR(25),
     NOMBREARTÍCULO VARCHAR(25),
     PRECIO INT(4),
     INSERTADO DATETIME
   );

   CREATE TRIGGER PRODUCTOS_AI 
   AFTER INSERT ON PRODUCTOS
   FOR EACH ROW
   INSERT INTO REG_PRODUCTOS(
     CÓDIGOARTÍCULO,
     NOMBREARTÍCULO,
     PRECIO,
     INSERTADO
   ) VALUES (
     NEW.CÓDIGOARTÍCULO,
     NEW.NOMBREARTÍCULO,
     NEW.PRECIO,
     NOW()
   );

INSERT INTO PRODUCTOS (CÓDIGOARTÍCULO, NOMBREARTÍCULO, PRECIO, PAÍSDEORIGEN)
VALUES ('AR75', 'PANTALÓN', 50,'ESPAÑA');


-- TRIGER DE ACTUALIZACIÓN
DROP TABLE IF EXISTS PRODUCTOS_ACTUALIZADOS;
CREATE TABLE PRODUCTOS_ACTUALIZADOS (
  ANTERIOR_CÓDIGOARTÍCULO VARCHAR(4),
  ANTERIOR_NOMBREARTÍCULO VARCHAR(15),
  ANTERIOR_SECCIÓN VARCHAR(20),
  ANTERIOR_PRECIO INT(4),
  ANTERIOR_IMPORTADO VARCHAR(15),
  ANTERIOR_PAÍSDEORIGEN VARCHAR(15),
  ANTERIOR_FECHA DATE,
  NUEVO_CÓDIGOARTÍCULO VARCHAR(4),
  NUEVO_NOMBREARTÍCULO VARCHAR(15),
  NUEVO_SECCIÓN VARCHAR(20),
  NUEVO_PRECIO INT(4),
  NUEVO_IMPORTADO VARCHAR(15),
  NUEVO_PAÍSDEORIGEN VARCHAR(15),
  NUEVO_FECHA DATE,
  USUARIO VARCHAR(15),
  F_MODIF DATE
);

CREATE TRIGGER ACTUALIZA_PRODUCTOS_BU
BEFORE UPDATE ON PRODUCTOS
FOR EACH ROW
INSERT INTO PRODUCTOS_ACTUALIZADOS(
  ANTERIOR_CÓDIGOARTÍCULO,
  ANTERIOR_FECHA,
  ANTERIOR_IMPORTADO,
  ANTERIOR_NOMBREARTÍCULO,
  ANTERIOR_PRECIO,
  ANTERIOR_PAÍSDEORIGEN,
  ANTERIOR_SECCIÓN,
  NUEVO_CÓDIGOARTÍCULO,
  NUEVO_FECHA,
  NUEVO_IMPORTADO,
  NUEVO_NOMBREARTÍCULO, 
  NUEVO_PRECIO, 
  NUEVO_PAÍSDEORIGEN,
  NUEVO_SECCIÓN, 
  USUARIO,
  F_MODIF
  ) VALUES (
    OLD.CÓDIGOARTÍCULO,
    OLD.FECHA,
    OLD.IMPORTADO,
    OLD.NOMBREARTÍCULO,
    OLD.PRECIO,
    OLD.PAÍSDEORIGEN,
    OLD.SECCIÓN,
    NEW.CÓDIGOARTÍCULO,
    NEW.FECHA,
    NEW.IMPORTADO,
    NEW.NOMBREARTÍCULO, 
    NEW.PRECIO, 
    NEW.PAÍSDEORIGEN,
    NEW.SECCIÓN, 
    CURRENT_USER,
    NOW()
  );

  UPDATE PRODUCTOS
  SET PRECIO = PRECIO+20
  WHERE CÓDIGOARTÍCULO = 'AR07';


-- TRIGER DE ELIMINACIÓN
DROP TABLE IF EXISTS PROD_ELIMINADOS;
CREATE TABLE PROD_ELIMINADOS(
  C_ART VARCHAR(5),
  NOMBRE VARCHAR(25),
  SECCIÓN VARCHAR(15),
  PRECIO INTEGER,
  PAÍSDEORIGEN VARCHAR(15)
);

DROP TRIGGER IF EXISTS ELIMPROD_AD;
CREATE TRIGGER ELIMPROD_AD 
AFTER DELETE ON PRODUCTOS
FOR EACH ROW
INSERT INTO PROD_ELIMINADOS (
  C_ART, NOMBRE, PAÍSDEORIGEN, PRECIO, SECCIÓN, USUARIO, FECHA_MODIF
) VALUES (
  OLD.CÓDIGOARTÍCULO, OLD.NOMBREARTÍCULO,
  OLD.PAÍSDEORIGEN, OLD.PRECIO, OLD.SECCIÓN,
  CURRENT_USER, NOW()
);

ALTER TABLE PROD_ELIMINADOS
ADD COLUMN (
  USUARIO VARCHAR(15),
  FECHA_MODIF DATE
);

DELETE FROM PRODUCTOS
WHERE CÓDIGOARTÍCULO = 'AR75';

DELETE FROM PRODUCTOS
WHERE CÓDIGOARTÍCULO = 'AR27';






-- ELIMINACIÓN DE TRIGGERS

-- MODIFICACIÓN DE TIRGGERS
