-- VISTAS
  -- ventajas: privacidade la informacion,
  -- optimización de la bd, entorno de pruebas.

  CREATE VIEW ART_DEPORTES AS
  SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO
  FROM PRODUCTOS
  WHERE SECCIÓN = 'DEPORTES';

  UPDATE PRODUCTOS
  SET PRECIO = PRECIO+10
  WHERE NOMBREARTÍCULO = 'RAQUETA TENIS';

  CREATE VIEW ART_CERAMICA AS
  SELECT NOMBREARTÍCULO, SECCIÓN, PRECIO
  FROM PRODUCTOS
  WHERE SECCIÓN = 'CERÁMICA';

  DROP VIEW ART_CERAMICA;

  ALTER VIEW ART_DEPORTES AS
  SELECT NOMBREARTÍCULO, SECCIÓN, PAÍSDEORIGEN
  FROM PRODUCTOS
  WHERE PAÍSDEORIGEN = 'ESPAÑA';