-- REFERENCIAS CRUZADAS 

-- es una tala dinamica tipo excel

-- Para los campos se utiliza:
  -- GROUP BY para las filas
  -- PIVOT para las columnas
  -- TRANSFORM para totales


-- MYSQL NO ADMITE ESTE TIPOS DE CONSULTAS
-- ACCESS SI

TRANSFORM SUM(PRECIO) AS TOTAL
SELECT NOMBREARTÍCULO
FROM PRODUCTOS
GROUP BY NOMBREARTÍCULO
PIVOT SECCIÓN;


TRANSFORM SUM(PRECIO) AS TOTAL
SELECT SECCIÓN
FROM PRODUCTOS
GROUP BY SECCIÓN
PIVOT NOMBREARTÍCULO;


TRANSFORM COUNT(CÓDIGOARTÍCULO) AS N_ARTICULOS
SELECT NOMBREARTÍCULO
FROM PRODUCTOS
GROUP BY NOMBREARTÍCULO
PIVOT SECCIÓN;

----------------------------------

SELECT EMPRESA, POBLACIÓN, FORMADEPAGO
FROM CLIENTES 
INNER JOIN PEDIDOS 
ON CLIENTES.CÓDIGOCLIENTE = PEDIDOS.CÓDIGOCLIENTE;

TRANSFORM SUM(PRECIO) AS TOTAL
SELECT NOMBRE(ARTÍCULO, PAÍSDEORIGEN)
FROM PRODUCTOS
GROUP BY NOMBREARTÍCULO, PAÍSDEORIGEN
PIVOT SECCIÓN;
