-- COMANDOS DDL. DATA DEFINITION LANGUANJE.
-- DEFINICIÓN DE DATOS

-- CREATE, ALTER, DROP, TRUNCATE -> BORRA TODAS LAS FILAS


 -- TABLAS BASE - PERSISTENTES


-- MYSQL
DROP TABLE IF EXISTS PRUEBA;
 CREATE TABLE PRUEBA (
   ID_ALUMNO INT AUTO_INCREMENT,
   NOMBRE VARCHAR(20),
   APELLIDO VARCHAR(20),
   EDAD TINYINT,
   FECHA_NACIMIENTO DATE,
   CARNET BOOL,
   PRIMARY KEY(ID_ALUMNO)
 );

-- ACCESS
DROP TABLE IF EXISTS PRUEBA;
 CREATE TABLE PRUEBA(
   ID_ALUMNO COUNTER,
   NOMBRE TEXT(20),
   APELLIDO TEXT(20),
   EDAD BYTE,
   FECHA_NACIMIENTO DATE,
   CARNET BIT
 );
