DROP PROCEDURE IF EXISTS JUBILAR;
DELIMITER //

CREATE PROCEDURE JUBILAR()
BEGIN
DECLARE NPLAZAS INT;
DECLARE FIN INT DEFAULT 0;
DECLARE VAL_CURP VARCHAR(255);
DECLARE VAL_ID_PERSONA VARCHAR(255);
DECLARE VAL_CLAVE_CT VARCHAR(255);
 DECLARE counter INT DEFAULT 0;
  DECLARE IP VARCHAR(60);
  DECLARE CP VARCHAR(60);
  DECLARE CT VARCHAR(60);

DECLARE CUR CURSOR FOR 
SELECT CURP, ID_PERSONA, CLAVE_CT,cast(NUM_PLAZAS as unsigned)
FROM CEMABE_PERSONAL
WHERE NUM_PLAZAS > 0  
AND EDAD >= 60
FOR UPDATE;

DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIN =  1;

OPEN CUR;

REPEAT

FETCH CUR INTO VAL_CURP, VAL_ID_PERSONA, VAL_CLAVE_CT, NPLAZAS;

UPDATE CEMABE_PERSONAL SET NUM_PLAZAS = 0, estatus = 3, IMPARTE_CLASES=0 WHERE CURP = VAL_CURP AND ID_PERSONA = VAL_ID_PERSONA AND CLAVE_CT=VAL_CLAVE_CT;

  SET COUNTER = NPLAZAS;
  my_loop: LOOP
  
    set IP = (SELECT ID_PERSONA FROM CEMABE_PERSONAL WHERE NUM_PLAZAS = 0 AND EDAD < 40  LIMIT 1);
    set CP = (SELECT CURP FROM CEMABE_PERSONAL WHERE NUM_PLAZAS = 0 AND EDAD < 40 LIMIT 1);
    set CT = (SELECT CLAVE_CT FROM CEMABE_PERSONAL WHERE NUM_PLAZAS = 0 AND EDAD < 40 LIMIT 1);
  

    UPDATE CEMABE_PERSONAL SET NUM_PLAZAS = 1, estatus = 1, IMPARTE_CLASES=2 
    WHERE CURP = CP AND ID_PERSONA = IP AND CLAVE_CT=CT;


    SET counter=COUNTER-1;


 
    IF counter=0 THEN
      LEAVE my_loop;
    END IF;



  END LOOP my_loop;

UNTIL FIN = 1 END REPEAT;
CLOSE CUR;

END
//

DELIMITER ;
---------------------------------------

 
  
   
    

---------------------------------------------------------------------------------------------------------------------------------
DROP TABLE IF EXISTS AUDIT_MAESTROS_AI;
CREATE TABLE AUDIT_MAESTROS_AI(
AUDIT_DATE TIMESTAMP,
AUDIT_USER VARCHAR(40)  NOT NULL,
AUDIT_ACTION ENUM('update','delete','insert'),
CLAVE_CT VARCHAR(23) NOT NULL,
ID_PERSONA VARCHAR(7) NOT NULL,
CURP VARCHAR(24) NOT NULL,
NP INT NOT NULL,
IMPARTE_CLASES VARCHAR(1) NOT NULL,
ESTATUS INT NOT NULL
);

DROP TABLE IF EXISTS AUDIT_MAESTROS_BU;
CREATE TABLE AUDIT_MAESTROS_BU(
AUDIT_DATE TIMESTAMP,
AUDIT_USER VARCHAR(40)  NOT NULL,
AUDIT_ACTION ENUM('update','delete','insert'),
CLAVE_CT VARCHAR(23) NOT NULL,
ID_PERSONA VARCHAR(7) NOT NULL,
CURP VARCHAR(24) NOT NULL,
NP INT NOT NULL,
IMPARTE_CLASES VARCHAR(1) NOT NULL,
ESTATUS INT NOT NULL
);

-------------------------------------------------------------------------------------------------------------------------------------
DROP TRIGGER IF EXISTS TG_CONTROLMAESTROS_AU;
CREATE TRIGGER TG_CONTROLMAESTROS_AI
AFTER UPDATE ON CEMABE_PERSONAL
FOR EACH ROW
INSERT INTO AUDIT_MAESTROS_AI
(AUDIT_USER, AUDIT_ACTION, CLAVE_CT, ID_PERSONA, CURP, NP, IMPARTE_CLASES, ESTATUS) VALUES
(CURRENT_USER(), 'update', NEW.CLAVE_CT, NEW.ID_PERSONA, NEW.CURP,
NEW.NUM_PLAZAS, NEW.IMPARTE_CLASES, NEW.ESTATUS );


DROP TRIGGER IF EXISTS TG_CONTROLMAESTROS_BU;
CREATE TRIGGER TG_CONTROLMAESTROS_BU
BEFORE UPDATE ON CEMABE_PERSONAL
FOR EACH ROW
INSERT INTO AUDIT_MAESTROS_BU2
(AUDIT_USER, AUDIT_ACTION, CLAVE_CT, ID_PERSONA, CURP, NUM_PLAZAS, IMPARTE_CLASES, ESTATUS) VALUES
(CURRENT_USER(), 'update', OLD.CLAVE_CT, OLD.ID_PERSONA, OLD.CURP,
OLD.NUM_PLAZAS, OLD.IMPARTE_CLASES, OLD.ESTATUS );







ALTER TABLE CEMABE_PERSONAL ADD( 
ESTATUS INT NOT NULL
);
-------------------------------------------------
DROP PROCEDURE IF EXISTS JUBILAR;
DELIMITER //

CREATE PROCEDURE JUBILAR()
BLOCK1:BEGIN
DECLARE NPLAZAS INT;
DECLARE FIN INT DEFAULT 0;
DECLARE FIN2 INT DEFAULT 0;
DECLARE SUM INT DEFAULT 0;
DECLARE VAL_CURP VARCHAR(255);
DECLARE VAL_ID_PERSONA VARCHAR(255);
DECLARE VAL_CLAVE_CT VARCHAR(255);
 DECLARE counter INT DEFAULT 0;
  DECLARE IP VARCHAR(60);
  DECLARE CP VARCHAR(60);
  DECLARE CT VARCHAR(60);

DECLARE CUR CURSOR FOR 
SELECT CURP, ID_PERSONA, CLAVE_CT,cast(NUM_PLAZAS as unsigned)
FROM CEMABE_PERSONAL
WHERE NUM_PLAZAS > 0  
AND EDAD >= 60
FOR UPDATE;

DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIN =  1;

OPEN CUR;

REPEAT

FETCH CUR INTO VAL_CURP, VAL_ID_PERSONA, VAL_CLAVE_CT, NPLAZAS;

UPDATE CEMABE_PERSONAL SET NP = 0, estatus = 3, IC=0 WHERE CURP = VAL_CURP AND ID_PERSONA = VAL_ID_PERSONA AND CLAVE_CT=VAL_CLAVE_CT;
 

  BLOCK2: BEGIN

  DECLARE CUR2 CURSOR FOR 
  SELECT ID_PERSONA, CLAVE_CT, CURP FROM CEMABE_PERSONAL 
  WHERE NUM_PLAZAS = 0 
  AND EDAD < 40 
  LIMIT NPLAZAS;

  DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIN2 =  1;

  OPEN CUR2;

  REPEAT

  FETCH CUR2 INTO IP, CP, CT;

 
    UPDATE CEMABE_PERSONAL SET NP = 1, estatus = 1, IC=2 
    WHERE CURP = CP AND ID_PERSONA = IP AND CLAVE_CT=CT;
    
    UNTIL FIN2 = 1 END REPEAT;
    CLOSE CUR2;
    END BLOCK2;

 

UNTIL FIN = 1 END REPEAT;
CLOSE CUR;

END BLOCK1;
//

DELIMITER ;


----------------------------

CREATE VIEW MAE_JUBILADOS AS 
SELECT CLAVE_CT, ID_PERSONA, CURP, AP_PATERNO, AP_MATERNO, NOMBRE_MAE, ESTATUS, FECHA_NAC, EDAD 
FROM CEMABE_PERSONAL 
WHERE ESTATUS = 3 
GROUP BY AP_PATERNO;