DROP FUNCTION IF EXISTS HOROSCOPO_CHINO;
DELIMITER //
CREATE FUNCTION HOROSCOPO_CHINO(VAL_FECHA VARCHAR(10)) RETURNS VARCHAR(30)
BEGIN
--declaracion de variables
DECLARE VAL_FECHA_NAC DATE;
DECLARE ANYO_NAC INT;
DECLARE RESTO FLOAT;
DECLARE ANIMAL VARCHAR(20);
DECLARE ELEMENTO VARCHAR(20);
DECLARE ULTIMO_DIGITO INT DEFAULT 0;
DECLARE HOROSCOPO VARCHAR(50);

--el parametro fecha lo convertimos a tipo DATE
SET VAL_FECHA_NAC = STR_TO_DATE(VAL_FECHA, '%d/%m/%Y');
--con la funcion YEAR obtenemos el año de la fecha del parametro
SET ANYO_NAC = YEAR(VAL_FECHA_NAC);
--con esta formula se calcula el animal correspondiente
SET RESTO = (ANYO_NAC%12);

--dependiendo del numero guardado en resto se asigna un animal
IF(RESTO = 0) THEN SET ANIMAL = 'MONO';
ELSEIF(RESTO = 1) THEN SET ANIMAL = 'GALLO';
ELSEIF(RESTO = 2) THEN SET ANIMAL = 'PERRO';
ELSEIF(RESTO = 3) THEN SET ANIMAL = 'CERDO';
ELSEIF(RESTO = 4) THEN SET ANIMAL = 'RATA';
ELSEIF(RESTO = 5) THEN SET ANIMAL = 'BUEY';
ELSEIF(RESTO = 6) THEN SET ANIMAL = 'TIGRE';
ELSEIF(RESTO = 7) THEN SET ANIMAL = 'CONEJO';
ELSEIF(RESTO = 8) THEN SET ANIMAL = 'DRAGON';
ELSEIF(RESTO = 9) THEN SET ANIMAL = 'SERPIENTE';
ELSEIF(RESTO = 10) THEN SET ANIMAL = 'CABALLO';
ELSEIF(RESTO = 11) THEN SET ANIMAL = 'CABRA';
END IF;

--me diante la funcion substring se obtiene el ultimo digito del año
--para determinar el elemento correspondiente
SET ULTIMO_DIGITO = (SUBSTRING(ANYO_NAC,4,1));

--en base al resultado almacenado se asigna un elemento
IF(ULTIMO_DIGITO = 0 OR ULTIMO_DIGITO = 1) THEN SET ELEMENTO = 'METAL';
ELSEIF(ULTIMO_DIGITO = 2 OR ULTIMO_DIGITO = 3) THEN SET ELEMENTO = 'AGUA';
ELSEIF(ULTIMO_DIGITO = 4 OR ULTIMO_DIGITO = 5) THEN SET ELEMENTO = 'MADERA';
ELSEIF(ULTIMO_DIGITO = 6 OR ULTIMO_DIGITO = 7) THEN SET ELEMENTO = 'FUEGO';
ELSEIF(ULTIMO_DIGITO = 8 OR ULTIMO_DIGITO = 9) THEN SET ELEMENTO = 'TIERRA';
END IF;

--regresa elemento y animal correspondiente al año de nacimiento
SET HOROSCOPO = CONCAT(ANIMAL, ' DE ', ELEMENTO);

RETURN HOROSCOPO;

END //
DELIMITER ;

--VISTA
CREATE VIEW HOROSCOPO_CHINO AS
SELECT AP_PATERNO, AP_MATERNO, NOMBRE_MAE,FECHA_NAC,HOROSCOPO_CHINO(FECHA_NAC) 
AS HOROSCOPO_CHINO 
FROM CEMABE_PERSONAL WHERE CURP <> '' 
AND FECHA_NAC <> '';

