DROP FUNCTION IF EXISTS SIGNO_ZODIACAL;
DELIMITER //
CREATE FUNCTION SIGNO_ZODIACAL(VAL_FECHA VARCHAR(10)) RETURNS VARCHAR(30)
BEGIN
--declaracion de variables
DECLARE VAL_FECHA_NAC DATE;
DECLARE MES INT DEFAULT 0;
DECLARE DIA INT DEFAULT 0;
DECLARE SIGNO VARCHAR(20);

--se conviterte el parametro recibido a tipo DATE
SET VAL_FECHA_NAC = STR_TO_DATE(VAL_FECHA, '%d/%m/%Y');

--se toma el mes de la fecha
SET MES = MONTH(VAL_FECHA_NAC);

--se toma el dia de la fecha
SET DIA = DAY(VAL_FECHA_NAC);

--En base a las variables se determina el signo
IF (MES = 1) THEN
	IF (DIA  > 21) THEN SET SIGNO = 'ACUARIO';
	ELSE SET SIGNO = 'CAPRICORNIO';
	END IF;
ELSEIF (MES = 2) THEN
	IF (DIA  > 19) THEN SET SIGNO = 'PISCIS';
	ELSE SET SIGNO = 'ACUARIO';
	END IF;
ELSEIF (MES = 3) THEN
	IF (DIA  > 21) THEN SET SIGNO = 'ARIES';
	ELSE SET SIGNO = 'PISCIS';
	END IF;
ELSEIF (MES = 4) THEN
	IF (DIA  > 20) THEN SET SIGNO = 'TAURO';
	ELSE SET SIGNO = 'ARIES';
	END IF;
ELSEIF (MES = 5) THEN
	IF (DIA  > 21) THEN SET SIGNO = 'GEMINIS';
	ELSE SET SIGNO = 'TAURO';
	END IF;
ELSEIF (MES = 6) THEN
	IF (DIA  > 20) THEN SET SIGNO = 'CANCER';
	ELSE SET SIGNO = 'GEMINIS';
	END IF;
ELSEIF (MES = 7) THEN
	IF (DIA  > 22) THEN SET SIGNO = 'LEO';
	ELSE SET SIGNO = 'CANCER';
	END IF;
ELSEIF (MES = 8) THEN
	IF (DIA  > 21) THEN SET SIGNO = 'VIRGO';
	ELSE SET SIGNO = 'LEO';
	END IF;
ELSEIF (MES = 9) THEN
	IF (DIA  > 22) THEN SET SIGNO = 'LIBRA';
	ELSE SET SIGNO = 'VIRGO';
	END IF;
ELSEIF (MES = 10) THEN
	IF (DIA  > 22) THEN SET SIGNO = 'ESCORPION';
	ELSE SET SIGNO = 'LIBRA';
	END IF;
ELSEIF (MES = 11) THEN
	IF (DIA  > 21) THEN SET SIGNO = 'SAGITARIO';
	ELSE SET SIGNO = 'ESCORPION';
	END IF;
ELSEIF (MES = 12) THEN
	IF (DIA  > 21) THEN SET SIGNO = 'CAPRICORNIO';
	ELSE SET SIGNO = 'SAGITARIO';
	END IF;
END IF;

RETURN SIGNO;

END //
DELIMITER ;


-------------------------------------
--vista
CREATE VIEW SIGNO_ZODIACAL AS 
SELECT AP_PATERNO, AP_MATERNO, NOMBRE_MAE,FECHA_NAC,SIGNO_ZODIACAL(FECHA_NAC) AS SIGNO_ZODIACAL
FROM CEMABE_PERSONAL WHERE CURP <> '' AND FECHA_NAC <> '';